#! /bin/sh

ln -sf /usr/share/webext/toopie@eyedeekay.github.io \
/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/toopie@eyedeekay.github.io

touch /usr/share/webext/toopie@eyedeekay.github.io/manifest.json
